name: Jellyfin Direct Play Converter
slug: jellyfin-directplay-converter
description: Post-process media for Jellyfin (AC3â†’AAC, remuxing, etc)
version: "0.1.6"
startup: services
boot: auto
init: false
arch:
  - aarch64
  - armv7
  - amd64
map:
  - share:rw
  - media:rw
options:
  scan_interval: 15
  movies_path: /share/jellyfin/movies
  tv_path: /share/jellyfin/tv
schema:
  scan_interval: int(5,1440)
  movies_path: str
  tv_path: str
